import { Inter } from "next/font/google";
import "./styles/globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Stats",
  description: "Generated by Ben",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-around p-8">
          <div className="bg"></div>
          <div className="z-30 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
            <p className="fixed left-0 top-0 flex w-full justify-center border-b bg-gradient-to-b pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:p-4 lg:dark:bg-zinc-800/30">
              <code className="font-mono font-bold">My Stats</code>
            </p>
            <div className="fixed h-10 left-0 bottom-0 flex w-full justify-center align-middle border-b bg-gradient-to-b pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:p-4 lg:dark:bg-zinc-800/30">
              <a
                className="pointer-events-none flex place-items-center lg:pointer-events-auto lg:p-0"
                href="https://vercel.com?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Mise à jour le 28/11/2023
              </a>
            </div>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
